SELECT REC.DIA3||'/'||REC.MES3||'/'||REC.ANN3 AS "FECHA RECEPCION",
PRO.NOM1||' '||PRO.AP1||' '||PRO.AP2 AS "NOMBRE PROVEEDOR",
PRO.RUT1||'-'||PRO.DV1 AS "RUT PROVEEDOR",
GUIA.N2 AS "NUMERO GUÍA",
CAR.MR AS "METROS RUMA RECEPCIONADOS"
FROM REC
INNER JOIN PRO ON REC.PRO_RUT1 = PRO.RUT1
INNER JOIN GUIA ON REC.GUIA_N2 = GUIA.N2
INNER JOIN CAR ON REC.CAR_ID1 = CAR.ID1;

SELECT PRO.NOM1||' '||PRO.AP1||' '||PRO.AP2 AS PROVEEDOR,
SUM(CAR.MR) AS "METROS RUMA RECEPCIONADOS" FROM REC
INNER JOIN PRO
ON REC.PRO_RUT1 = PRO.RUT1
INNER JOIN CAR
ON REC.CAR_ID1 = CAR.ID1
WHERE TO_DATE(REC.DIA3||'-'||REC.MES3||'-'||REC.ANN3) BETWEEN '&FECHA1' and '&FECHA2'
GROUP BY PRO.NOM1, PRO.AP1, PRO.AP2;

SELECT SUM(CAR.MR) AS "METROS RUMA RECEPCIONADOS" FROM REC 
INNER JOIN CAR
ON REC.CAR_ID1 = CAR.ID1
WHERE TO_DATE(REC.DIA3||'-'||REC.MES3||'-'||REC.ANN3, 'DD-MM-YYYY') = '&FECHA';